### ISSUE TITLE
CI stuff

### ISSUE THREAD

**Issue by philipcraig** [evmar/n2#15]
Hi @evmar, would you welcome CI PRs to:

1. build and test against stable, beta and nightly Rust on ubuntu
2. check rustfmt and go red if failed
3. run clippy and go red if failed
4. report on outdated dependencies (but it would not go read as the out-of-dateness happens asynchronously with respect to repo changes)

Or you are fine without these things, which is also fine? Happy to send any PRs that are welcomed

**Comment by evmar** [comment]
Thanks for the offer, I appreciate it!

1. I am not sure, is it valuable?  I don't expect new Rust releases to break this.
2. It's a good idea, I think I implemented that here: https://github.com/evmar/n2/commit/1250092a32ee8ebd2b3c82c6f413f7d9312906f3
3. I am not sure about this one.  I ran clippy manually once or twice but I don't recall what it found was too valuable.  Is there a way to turn on clippy checks during normal builds?
4. Does dependabot handle this?

**Comment by philipcraig** [comment]
1. Fair enough
2. Yes, closed
3. A normal build locally or on CI? The clippy check step is `cargo clippy --workspace --tests -- -Dclippy::all`
4. Yes, it should, if you turn it on

**Comment by evmar** [comment]
I think if I turn clippy on in CI but not in local builds then it is basically another thing that can break.  I think I'm ok with just running it manually for now.

I see dependabot alerts for JS on this repo, so I imagine it must be scanning Rust too?

**Comment by philipcraig** [comment]
Yes, all sounds good
