### ISSUE TITLE
Hardcoded buffer size is too small for some builds

### ISSUE THREAD

**Issue by sztomi** [evmar/n2#17]
I tried to build a moderately sized project with a high number of files copied and compiled by the build. I don't know how this buffer is used:

```rs
struct WriteBuf {
    buf: [u8; 8192],
    len: usize,
}
```

but it led to panicing halfway during the build. Bumping it to twice the size fixed the panics. Happy to gather more information, but the source tree I was building is unfortunately not public.

**Comment by piscisaureus** [comment]
Does #18 fix it?

**Comment by evmar** [comment]
This buffer is used to write out:
- individual paths, which are limited to PATH_MAX=4kb, so it shouldn't have hit
- the lists of discovered dependencies, as found in a .d file generated by the compiler, 3 bytes per file.  Is it possible you have a build target that depends on >2500 headers?

It's definitely a bug, but I am kinda curious how it ended up triggering.

**Comment by sztomi** [comment]
@piscisaureus yes, it looks like that PR fixes it!

@evmar We have a resource file copying target that might exceed this limit by virtue of listing a huge number of files. Although, the resource copying happens before the actual compilation of sources begin and it's somewhere in that stage when it breaks.

I can email you the build.ninja and anything else you might need if you'd like to look into this (probably the .n2_db I'm guessing?). FYI, this is the stacktrace: 

```
thread 'main' panicked at 'range end index 8194 out of range for slice of length 8192', src/db.rs:76:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/slice/index.rs:43:5
   3: n2::db::Writer::write_build
   4: n2::work::Work::record_finished
             at /home/tamas/src/n2/src/work.rs:462:9
   5: n2::work::Work::run_without_cleanup
             at /home/tamas/src/n2/src/work.rs:710:13
   6: n2::work::Work::run
             at /home/tamas/src/n2/src/work.rs:723:22
   7: n2::build::{{closure}}
             at /home/tamas/src/n2/src/main.rs:71:42
   8: n2::trace::scope
             at /home/tamas/src/n2/src/trace.rs:112:21
```

**Comment by evmar** [comment]
I think it doesn't matter too much, I was mostly just curious.  While we talk about serde I can at least bump this for now.  This thing goes on the stack while writing so its size is pretty irrelevant.  Now that I'm thinking about it, write performance is not in the hot path anyway, so this probably could just as well be a growable `Vec<>`.
