### ISSUE TITLE
Dependencies support

### ISSUE THREAD

**Issue by kvark** [evmar/n2#52]
Example (with Ninja) - https://lwn.net/Articles/706404/
```
    rule cc
      command = gcc -c -o $out $in -MMD -MF $out.d
      depfile = $out.d
      deps = gcc
```
In my case, it produces an error:
> clang: error: argument to '-MF' is missing (expected 1 value)

**Comment by Novum** [comment]
I looked at this and it seems like n2 isn't concatanating `$out` and the `.d` extension like Ninja.

If the dep file location is specified via a separate name, e.g. `$depfile` this works fine.
