### ISSUE TITLE
input filename reykjavík.md gets mangled

### ISSUE THREAD

**Issue by hober** [evmar/n2#55]
```n2: error: build.ninja:29705: input source/2019/05/reykjavÃ-­k.md missing```

I assume this is related to [this bit in the development doc](https://github.com/evmar/n2/blob/fe6c2d5eb1766ed829a50b56572fdb81cc5af3ae/doc/development.md#path-handling-and-unicode-safety).

**Comment by evmar** [comment]
Hey, thanks for trying it out!

I'm curious how you found this, and what are you looking at n2 for.

I haven't really touched it since I wrote my blog post about it: https://neugierig.org/software/blog/2022/03/n2.html

**Comment by evmar** [comment]
(Whoops, my "fix" above doesn't yet work, lemme try again...)

**Comment by evmar** [comment]
Follow up discussion on the Unicode thing, in case you're curious:

https://github.com/evmar/n2/commit/aed28b2ffb7a1d053679766e796700aa082b1799

**Comment by hober** [comment]
> Hey, thanks for trying it out!
> 
> I'm curious how you found this, and what are you looking at n2 for?
> 
> I haven't really touched it since I wrote my blog post about it: https://neugierig.org/software/blog/2022/03/n2.html

That post is how I ended up here! I'd been fighting a bit with Ninja re: it relying solely on mtime and your blog post was one of the top results for a google search for "ninja mtime".

**Comment by evmar** [comment]
Ah, funny.  It's possible there's some alternative way to get Ninja to do
what you want.

This project worked well enough for me to use it at my normal job (with a
midsized CMake project) but it also has some big missing pieces like the
one you hit that probably mean it wouldn't be my first choice to use,
unless you were interested in potentially debugging/adding functionality to
it!
