### ISSUE TITLE
d64412ae74 can't be used to build clang/llvm anymore

### ISSUE THREAD

**Issue by durin42** [evmar/n2#56]
Bisecting, it looks like 6b4fb1a249a01891d68fcd9b6ceef1f2b3c788ba broke this. The failure is:

```
n2: error: parse error: expected '\n', got '.'
CMakeFiles/rules.ninja:119: rule CXX_COMPILER__obj.2eLLVMTableGenCom...
```

So it looks like between the mess that is llvm and #52 (which the breaking commit mentions it fixes) it's going to be a more complicated fix?

**Comment by durin42** [comment]
I just confirmed locally that backing out 6b4fb1a249a01891d68fcd9b6ceef1f2b3c788ba does let me build LLVM again, in case that's a useful datapoint.

**Comment by evmar** [comment]
Thanks for the report.  Are you using n2?  I haven't really touched it since my initial exploration, so I am happy if works for you but also surprised!

**Comment by durin42** [comment]
Yeah, it works for me very well, and the bazel-like output is very nice when I'm waiting on long builds of llvm. Thanks!

**Comment by evmar** [comment]
Cool!  I used it for months at my last job but I haven't had reason to run it recently.  Lemme know if you have any feature requests, I guess :P

**Comment by evmar** [comment]
Also man I just tried out LLVM, this is even on an M2:

<img width="527" alt="image" src="https://github.com/evmar/n2/assets/3847/842e1b36-5588-422e-b412-48de3dfeb790">
