### ISSUE TITLE
Commands fail with `CreateProcessA: The parameter is incorrect`

### ISSUE THREAD

**Issue by evmar** [evmar/n2#78]
@tru wrote:
> Every time n2 tries to execute a subprocess, it exits with CreateProcessA: The parameter is incorrect. this happens already when running cmake, and also when trying to build a small build.ninja without involving cmake.

I have tested a small build.ninja that invokes clang-cl and it worked for me, so I am not sure what's different here.
I checked that in here: https://github.com/evmar/n2/tree/main/tests/manual/clang-cl
@tru could you try running n2 on that dir and let me know if it works?

Some other possibilities:
- Which version of Windows?  Mine is Windows 10.

Next I'm eyeballing [n2 code](https://github.com/evmar/n2/blob/17ae509efcd2a9aed9e75a6bdedbae7f0d60bebb/src/process_win.rs#L189C12-L189C25) vs [similar ninja code](https://github.com/ninja-build/ninja/blob/36843d387cb0621c1a288179af223d4f1410be73/src/subprocess-win32.cc#L112)

**Comment by evmar** [comment]
https://github.com/ninja-build/ninja/pull/1637/files feels possibly related

**Comment by tru** [comment]
That example works fine on my machine, I have Windows 11, but I doubt that's related. It's probably some stupid argument quoting. Those things always trip me up as well. Can you add similar error handling in n2, and we can get more info on what's going wrong?

**Comment by evmar** [comment]
Also, can you paste the failing build.ninja you tried that didn't involve cmake?

**Comment by evmar** [comment]
(In case you missed it, I pushed a change that has more error handling, so please let me know if it helps.)

**Comment by dae** [comment]
FWIW, I was seeing that error when I tried the latest main branch a week or so ago, but it seems to be working fine now.

**Comment by tru** [comment]
Hi! Sorry for the late reply, but I was on vacation. I downloaded and ran the latest version and this problem seems to have been fixed!
