### ISSUE TITLE
StackStack is not drop safe

### ISSUE THREAD

**Issue by erickt** [evmar/n2#8]
I noticed that the implementation for [StackStack](https://github.com/evmar/n2/blob/main/src/canon.rs#L5) could lead to undefined behavior if any of the values have a drop implementation. I think you need to wrap the types in [ManuallyDrop](https://doc.rust-lang.org/stable/std/mem/struct.ManuallyDrop.html) to prevent the drop impls from being called on uninitialized values, or use one of the array-backed vec implementations, like https://docs.rs/arrayvec/latest/arrayvec/struct.ArrayVec.html, which implements this pattern for you.

**Comment by erickt** [comment]
Doing another pass through the code, you could also make StackStack only work with `*mut u8`, since I think that’s the only type you use it with.

**Comment by evmar** [comment]
Wow, thanks for looking!  I agree making it just work for *u8 is good. Alternatively it could track usize indexes instead of pointers at all, but that would cause array bounds checks when it’s used…

**Comment by evmar** [comment]
Thinking about this again, I think the only reason I made this generic is that it was easier to read (with a generic `T`), given that it doesn't care about what T is.  Would it be sufficient to constrain `T: Copy`, to mark T as non-droppable?

**Comment by erickt** [comment]
I don’t really know this area that well, but from what I understand from https://doc.rust-lang.org/reference/behavior-considered-undefined.html, the act of creating an uninitialized value may be undefined, even if it’s never touched. For example, &T is copy, but it’s UB if the value is ever null, even if it’s never read from. This part of the [rustonomicon](https://doc.rust-lang.org/nomicon/unchecked-uninit.html) talks about some of it.  

After doing a little more digging, the source of the problem here is actually the mem::uninitialized. Instead, switching to [MaybeUninit](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html), would force you to initialize the values correctly. arrayvec appears to be doing this correctly. So your safest bet is either using it or something like it, or copy the pattern it uses.

**Comment by evmar** [comment]
Ah, looking at the code I already had made this `T: Copy`, so I guess it was drop safe already.

I can switch it to MaybeUninit, that's ok too, but I think it's separate from the dropping thing.
