### ISSUE TITLE
Inconsistent handling of newline escapes

### ISSUE THREAD

**Issue by encounter** [evmar/n2#89]
Example:
```ninja
rule touch
  command = touch $out
build foo: $
  touch
```

Output:
```
$ ninja
[1/1] touch foo
$ n2
n2: error: parse error: failed to scan ident
build.ninja:3: build foo: $
                          ^
```

Would be nice to fix, [ninja_syntax.py](https://github.com/ninja-build/ninja/blob/master/misc/ninja_syntax.py) really likes to use wrapped newlines.

**Comment by evmar** [comment]
Thanks for the great report!

**Comment by evmar** [comment]
Looking at this code, I think it generally might do the wrong thing with windows-style newlines (which might predate this particular issue even).  I kind of doubt anyone cares, but if it does come up I will revisit it.
